package provider

var defaultProviders = map[string]Provider{
	"500px": Provider{
		Name:         "500px",
		RequestURL:   "https://api.500px.com/v1/oauth/request_token",
		AuthorizeURL: "https://api.500px.com/v1/oauth/authorize",
		AccessURL:    "https://api.500px.com/v1/oauth/access_token",
		OAuth:        1,
	},
	"amazon": Provider{
		Name:           "amazon",
		AuthorizeURL:   "https://www.amazon.com/ap/oa",
		AccessURL:      "https://api.amazon.com/auth/o2/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"angellist": Provider{
		Name:           "angellist",
		AuthorizeURL:   "https://angel.co/api/oauth/authorize",
		AccessURL:      "https://angel.co/api/oauth/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"appnet": Provider{
		Name:           "appnet",
		AuthorizeURL:   "https://account.app.net/oauth/authenticate",
		AccessURL:      "https://account.app.net/oauth/access_token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"asana": Provider{
		Name:         "asana",
		AuthorizeURL: "https://app.asana.com/-/oauth_authorize",
		AccessURL:    "https://app.asana.com/-/oauth_token",
		OAuth:        2,
	},
	"assembla": Provider{
		Name:         "assembla",
		AuthorizeURL: "https://api.assembla.com/authorization",
		AccessURL:    "https://_client_id:_client_secret@api.assembla.com/token",
		OAuth:        2,
	},
	"basecamp": Provider{
		Name:         "basecamp",
		AuthorizeURL: "https://launchpad.37signals.com/authorization/new",
		AccessURL:    "https://launchpad.37signals.com/authorization/token",
		OAuth:        2,
	},
	"bitbucket": Provider{
		Name:         "bitbucket",
		RequestURL:   "https://bitbucket.org/api/1.0/oauth/request_token",
		AuthorizeURL: "https://bitbucket.org/api/1.0/oauth/authenticate",
		AccessURL:    "https://bitbucket.org/api/1.0/oauth/access_token",
		OAuth:        1,
	},
	"bitly": Provider{
		Name:         "bitly",
		AuthorizeURL: "https://bitly.com/oauth/authorize",
		AccessURL:    "https://api-ssl.bitly.com/oauth/access_token",
		OAuth:        2,
	},
	"box": Provider{
		Name:         "box",
		AuthorizeURL: "https://api.box.com/oauth2/authorize",
		AccessURL:    "https://api.box.com/oauth2/token",
		OAuth:        2,
	},
	"buffer": Provider{
		Name:         "buffer",
		AuthorizeURL: "https://bufferapp.com/oauth2/authorize",
		AccessURL:    "https://api.bufferapp.com/1/oauth2/token.json",
		OAuth:        2,
	},
	"cheddar": Provider{
		Name:         "cheddar",
		AuthorizeURL: "https://api.cheddarapp.com/oauth/authorize",
		AccessURL:    "https://api.cheddarapp.com/oauth/token",
		OAuth:        2,
	},
	"coinbase": Provider{
		Name:             "coinbase",
		AuthorizeURL:     "https://www.coinbase.com/oauth/authorize",
		AccessURL:        "https://www.coinbase.com/oauth/token",
		OAuth:            2,
		ScopeDelimiter:   " ",
		CustomParameters: []string{"meta"},
	},
	"dailymile": Provider{
		Name:         "dailymile",
		AuthorizeURL: "https://api.dailymile.com/oauth/authorize",
		AccessURL:    "https://api.dailymile.com/oauth/token",
		OAuth:        2,
	},
	"dailymotion": Provider{
		Name:         "dailymotion",
		AuthorizeURL: "https://www.dailymotion.com/oauth/authorize",
		AccessURL:    "https://api.dailymotion.com/oauth/token",
		OAuth:        2,
	},
	"deezer": Provider{
		Name:         "deezer",
		AuthorizeURL: "https://connect.deezer.com/oauth/auth.php",
		AccessURL:    "https://connect.deezer.com/oauth/access_token.php",
		OAuth:        2,
	},
	"deviantart": Provider{
		Name:           "deviantart",
		AuthorizeURL:   "https://www.deviantart.com/oauth2/authorize",
		AccessURL:      "https://www.deviantart.com/oauth2/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"digitalocean": Provider{
		Name:           "digitalocean",
		AuthorizeURL:   "https://cloud.digitalocean.com/v1/oauth/authorize",
		AccessURL:      "https://cloud.digitalocean.com/v1/oauth/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"disqus": Provider{
		Name:         "disqus",
		AuthorizeURL: "https://disqus.com/api/oauth/2.0/authorize/",
		AccessURL:    "https://disqus.com/api/oauth/2.0/access_token/",
		OAuth:        2,
	},
	"dropbox": Provider{
		Name:         "dropbox",
		AuthorizeURL: "https://www.dropbox.com/1/oauth2/authorize",
		AccessURL:    "https://api.dropbox.com/1/oauth2/token",
		OAuth:        2,
	},
	"edmodo": Provider{
		Name:           "edmodo",
		AuthorizeURL:   "https://api.edmodo.com/oauth/authorize",
		AccessURL:      "https://api.edmodo.com/oauth/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"elance": Provider{
		Name:         "elance",
		AuthorizeURL: "https://api.elance.com/api2/oauth/authorize",
		AccessURL:    "https://api.elance.com/api2/oauth/token",
		OAuth:        2,
	},
	"eventbrite": Provider{
		Name:         "eventbrite",
		AuthorizeURL: "https://www.eventbrite.com/oauth/authorize",
		AccessURL:    "https://www.eventbrite.com/oauth/token",
		OAuth:        2,
	},
	"evernote": Provider{
		Name:         "evernote",
		RequestURL:   "https://www.evernote.com/oauth",
		AuthorizeURL: "https://www.evernote.com/OAuth.action",
		AccessURL:    "https://www.evernote.com/oauth",
		OAuth:        1,
	},
	"everyplay": Provider{
		Name:         "everyplay",
		AuthorizeURL: "https://everyplay.com/connect",
		AccessURL:    "https://api.everyplay.com/oauth2/access_token",
		OAuth:        2,
	},
	"eyeem": Provider{
		Name:         "eyeem",
		AuthorizeURL: "http://www.eyeem.com/oauth/authorize",
		AccessURL:    "http://api.eyeem.com/v2/oauth/token",
		OAuth:        2,
	},
	"facebook": Provider{
		Name:         "facebook",
		AuthorizeURL: "https://www.facebook.com/dialog/oauth",
		AccessURL:    "https://graph.facebook.com/oauth/access_token",
		OAuth:        2,
	},
	"feedly": Provider{
		Name:         "feedly",
		AuthorizeURL: "https://cloud.feedly.com/v3/auth/auth",
		AccessURL:    "http://cloud.feedly.com/v3/auth/token",
		OAuth:        2,
	},
	"fitbit": Provider{
		Name:         "fitbit",
		RequestURL:   "https://api.fitbit.com/oauth/request_token",
		AuthorizeURL: "https://www.fitbit.com/oauth/authorize",
		AccessURL:    "https://api.fitbit.com/oauth/access_token",
		OAuth:        1,
	},
	"flattr": Provider{
		Name:           "flattr",
		AuthorizeURL:   "https://flattr.com/oauth/authorize",
		AccessURL:      "https://flattr.com/oauth/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"flickr": Provider{
		Name:             "flickr",
		RequestURL:       "https://www.flickr.com/services/oauth/request_token",
		AuthorizeURL:     "https://www.flickr.com/services/oauth/authorize",
		AccessURL:        "https://www.flickr.com/services/oauth/access_token",
		OAuth:            1,
		CustomParameters: []string{"perms"},
	},
	"flowdock": Provider{
		Name:           "flowdock",
		AuthorizeURL:   "https://api.flowdock.com/oauth/authorize",
		AccessURL:      "https://api.flowdock.com/oauth/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"foursquare": Provider{
		Name:         "foursquare",
		AuthorizeURL: "https://foursquare.com/oauth2/authenticate",
		AccessURL:    "https://foursquare.com/oauth2/access_token",
		OAuth:        2,
	},
	"freshbooks": Provider{
		Name:         "freshbooks",
		RequestURL:   "https://[subdomain].freshbooks.com/oauth/oauth_request.php",
		AuthorizeURL: "https://[subdomain].freshbooks.com/oauth/oauth_authorize.php",
		AccessURL:    "https://[subdomain].freshbooks.com/oauth/oauth_access.php",
		OAuth:        1,
		Subdomain:    true,
	},
	"geeklist": Provider{
		Name:         "geeklist",
		RequestURL:   "http://api.geekli.st/v1/oauth/request_token",
		AuthorizeURL: "https://geekli.st/oauth/authorize",
		AccessURL:    "http://api.geekli.st/v1/oauth/access_token",
		OAuth:        1,
	},
	"getpocket": Provider{
		Name:         "getpocket",
		RequestURL:   "https://getpocket.com/v3/oauth/request",
		AuthorizeURL: "https://getpocket.com/auth/authorize",
		AccessURL:    "https://getpocket.com/v3/oauth/authorize",
	},
	"github": Provider{
		Name:         "github",
		AuthorizeURL: "https://github.com/login/oauth/authorize",
		AccessURL:    "https://github.com/login/oauth/access_token",
		OAuth:        2,
	},
	"gitter": Provider{
		Name:         "gitter",
		AuthorizeURL: "https://gitter.im/login/oauth/authorize",
		AccessURL:    "https://gitter.im/login/oauth/token",
		OAuth:        2,
	},
	"goodreads": Provider{
		Name:         "goodreads",
		RequestURL:   "http://www.goodreads.com/oauth/request_token",
		AuthorizeURL: "http://www.goodreads.com/oauth/authorize",
		AccessURL:    "http://www.goodreads.com/oauth/access_token",
		OAuth:        1,
	},
	"google": Provider{
		Name:             "google",
		AuthorizeURL:     "https://accounts.google.com/o/oauth2/auth",
		AccessURL:        "https://accounts.google.com/o/oauth2/token",
		OAuth:            2,
		ScopeDelimiter:   " ",
		CustomParameters: []string{"access_type"},
	},
	"harvest": Provider{
		Name:         "harvest",
		AuthorizeURL: "https://api.harvestapp.com/oauth2/authorize",
		AccessURL:    "https://api.harvestapp.com/oauth2/token",
		OAuth:        2,
	},
	"heroku": Provider{
		Name:         "heroku",
		AuthorizeURL: "https://id.heroku.com/oauth/authorize",
		AccessURL:    "https://id.heroku.com/oauth/token",
		OAuth:        2,
	},
	"imgur": Provider{
		Name:         "imgur",
		AuthorizeURL: "https://api.imgur.com/oauth2/authorize",
		AccessURL:    "https://api.imgur.com/oauth2/token",
		OAuth:        2,
	},
	"instagram": Provider{
		Name:           "instagram",
		AuthorizeURL:   "https://api.instagram.com/oauth/authorize",
		AccessURL:      "https://api.instagram.com/oauth/access_token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"jawbone": Provider{
		Name:           "jawbone",
		AuthorizeURL:   "https://jawbone.com/auth/oauth2/auth",
		AccessURL:      "https://jawbone.com/auth/oauth2/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"linkedin": Provider{
		Name:         "linkedin",
		RequestURL:   "https://api.linkedin.com/uas/oauth/requestToken",
		AuthorizeURL: "https://www.linkedin.com/uas/oauth/authenticate",
		AccessURL:    "https://api.linkedin.com/uas/oauth/accessToken",
		OAuth:        1,
	},
	"linkedin2": Provider{
		Name:           "linkedin2",
		AuthorizeURL:   "https://www.linkedin.com/uas/oauth2/authorization",
		AccessURL:      "https://www.linkedin.com/uas/oauth2/accessToken",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"live": Provider{
		Name:         "live",
		AuthorizeURL: "https://login.live.com/oauth20_authorize.srf",
		AccessURL:    "https://login.live.com/oauth20_token.srf",
		OAuth:        2,
	},
	"mailchimp": Provider{
		Name:         "mailchimp",
		AuthorizeURL: "https://login.mailchimp.com/oauth2/authorize",
		AccessURL:    "https://login.mailchimp.com/oauth2/token",
		OAuth:        2,
	},
	"meetup": Provider{
		Name:           "meetup",
		AuthorizeURL:   "https://secure.meetup.com/oauth2/authorize",
		AccessURL:      "https://secure.meetup.com/oauth2/access",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"mixcloud": Provider{
		Name:         "mixcloud",
		AuthorizeURL: "https://www.mixcloud.com/oauth/authorize",
		AccessURL:    "https://www.mixcloud.com/oauth/access_token",
		OAuth:        2,
	},
	"odesk": Provider{
		Name:         "odesk",
		RequestURL:   "https://www.odesk.com/api/auth/v1/oauth/token/request",
		AuthorizeURL: "https://www.odesk.com/services/api/auth",
		AccessURL:    "https://www.odesk.com/api/auth/v1/oauth/token/access",
		OAuth:        1,
	},
	"openstreetmap": Provider{
		Name:         "openstreetmap",
		RequestURL:   "http://www.openstreetmap.org/oauth/request_token",
		AuthorizeURL: "http://www.openstreetmap.org/oauth/authorize",
		AccessURL:    "http://www.openstreetmap.org/oauth/access_token",
		OAuth:        1,
	},
	"paypal": Provider{
		Name:           "paypal",
		AuthorizeURL:   "https://www.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize",
		AccessURL:      "https://api.paypal.com/v1/identity/openidconnect/tokenservice",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"podio": Provider{
		Name:         "podio",
		AuthorizeURL: "https://podio.com/oauth/authorize",
		AccessURL:    "https://podio.com/oauth/token",
		OAuth:        2,
	},
	"rdio": Provider{
		Name:         "rdio",
		RequestURL:   "http://api.rdio.com/oauth/request_token",
		AuthorizeURL: "https://www.rdio.com/oauth/authorize",
		AccessURL:    "http://api.rdio.com/oauth/access_token",
		OAuth:        1,
	},
	"redbooth": Provider{
		Name:         "redbooth",
		AuthorizeURL: "https://redbooth.com/oauth2/authorize",
		AccessURL:    "https://redbooth.com/oauth2/token",
		OAuth:        2,
	},
	"reddit": Provider{
		Name:             "reddit",
		AuthorizeURL:     "https://ssl.reddit.com/api/v1/authorize",
		AccessURL:        "https://ssl.reddit.com/api/v1/access_token",
		OAuth:            2,
		CustomParameters: []string{"duration"},
	},
	"runkeeper": Provider{
		Name:         "runkeeper",
		AuthorizeURL: "https://runkeeper.com/apps/authorize",
		AccessURL:    "https://runkeeper.com/apps/token",
		OAuth:        2,
	},
	"salesforce": Provider{
		Name:           "salesforce",
		AuthorizeURL:   "https://login.salesforce.com/services/oauth2/authorize",
		AccessURL:      "https://login.salesforce.com/services/oauth2/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"shopify": Provider{
		Name:         "shopify",
		AuthorizeURL: "https://[subdomain].myshopify.com/admin/oauth/authorize",
		AccessURL:    "https://[subdomain].myshopify.com/admin/oauth/access_token",
		OAuth:        2,
		Subdomain:    true,
	},
	"skyrock": Provider{
		Name:         "skyrock",
		RequestURL:   "https://api.skyrock.com/v2/oauth/initiate",
		AuthorizeURL: "https://api.skyrock.com/v2/oauth/authorize",
		AccessURL:    "https://api.skyrock.com/v2/oauth/token",
		OAuth:        1,
	},
	"slack": Provider{
		Name:         "slack",
		AuthorizeURL: "https://slack.com/oauth/authorize",
		AccessURL:    "https://slack.com/api/oauth.access",
		OAuth:        2,
	},
	"slice": Provider{
		Name:         "slice",
		AuthorizeURL: "https://api.slice.com/oauth/authorize",
		AccessURL:    "https://api.slice.com/oauth/token",
		OAuth:        2,
	},
	"soundcloud": Provider{
		Name:         "soundcloud",
		AuthorizeURL: "https://soundcloud.com/connect",
		AccessURL:    "https://api.soundcloud.com/oauth2/token",
		OAuth:        2,
	},
	"spotify": Provider{
		Name:             "spotify",
		AuthorizeURL:     "https://accounts.spotify.com/authorize",
		AccessURL:        "https://accounts.spotify.com/api/token",
		OAuth:            2,
		ScopeDelimiter:   " ",
		CustomParameters: []string{"show_dialog"},
	},
	"stackexchange": Provider{
		Name:         "stackexchange",
		AuthorizeURL: "https://stackexchange.com/oauth",
		AccessURL:    "https://stackexchange.com/oauth/access_token",
		OAuth:        2,
	},
	"stocktwits": Provider{
		Name:         "stocktwits",
		AuthorizeURL: "https://api.stocktwits.com/api/2/oauth/authorize",
		AccessURL:    "https://api.stocktwits.com/api/2/oauth/token",
		OAuth:        2,
	},
	"strava": Provider{
		Name:         "strava",
		AuthorizeURL: "https://www.strava.com/oauth/authorize",
		AccessURL:    "https://www.strava.com/oauth/token",
		OAuth:        2,
	},
	"stripe": Provider{
		Name:         "stripe",
		AuthorizeURL: "https://connect.stripe.com/oauth/authorize",
		AccessURL:    "https://connect.stripe.com/oauth/token",
		OAuth:        2,
	},
	"traxo": Provider{
		Name:         "traxo",
		AuthorizeURL: "https://www.traxo.com/oauth/authenticate",
		AccessURL:    "https://www.traxo.com/oauth/token",
		OAuth:        2,
	},
	"trello": Provider{
		Name:             "trello",
		RequestURL:       "https://trello.com/1/OAuthGetRequestToken",
		AuthorizeURL:     "https://trello.com/1/OAuthAuthorizeToken",
		AccessURL:        "https://trello.com/1/OAuthGetAccessToken",
		OAuth:            1,
		CustomParameters: []string{"scope", "expiration"},
	},
	"tripit": Provider{
		Name:         "tripit",
		RequestURL:   "https://api.tripit.com/oauth/request_token",
		AuthorizeURL: "https://www.tripit.com/oauth/authorize",
		AccessURL:    "https://api.tripit.com/oauth/access_token",
		OAuth:        1,
	},
	"tumblr": Provider{
		Name:         "tumblr",
		RequestURL:   "http://www.tumblr.com/oauth/request_token",
		AuthorizeURL: "http://www.tumblr.com/oauth/authorize",
		AccessURL:    "http://www.tumblr.com/oauth/access_token",
		OAuth:        1,
	},
	"twitch": Provider{
		Name:           "twitch",
		AuthorizeURL:   "https://api.twitch.tv/kraken/oauth2/authorize",
		AccessURL:      "https://api.twitch.tv/kraken/oauth2/token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"twitter": Provider{
		Name:         "twitter",
		RequestURL:   "https://api.twitter.com/oauth/request_token",
		AuthorizeURL: "https://api.twitter.com/oauth/authenticate",
		AccessURL:    "https://api.twitter.com/oauth/access_token",
		OAuth:        1,
	},
	"uber": Provider{
		Name:         "uber",
		AuthorizeURL: "https://login.uber.com/oauth/authorize",
		AccessURL:    "https://login.uber.com/oauth/token",
		OAuth:        2,
	},
	"vimeo": Provider{
		Name:           "vimeo",
		AuthorizeURL:   "https://api.vimeo.com/oauth/authorize",
		AccessURL:      "https://api.vimeo.com/oauth/access_token",
		OAuth:          2,
		ScopeDelimiter: " ",
	},
	"vk": Provider{
		Name:         "vk",
		AuthorizeURL: "https://oauth.vk.com/authorize",
		AccessURL:    "https://oauth.vk.com/access_token",
		OAuth:        2,
	},
	"withings": Provider{
		Name:         "withings",
		RequestURL:   "https://oauth.withings.com/account/request_token",
		AuthorizeURL: "https://oauth.withings.com/account/authorize",
		AccessURL:    "https://oauth.withings.com/account/access_token",
		OAuth:        1,
	},
	"wordpress": Provider{
		Name:             "wordpress",
		AuthorizeURL:     "https://public-api.wordpress.com/oauth2/authorize",
		AccessURL:        "https://public-api.wordpress.com/oauth2/token",
		OAuth:            2,
		CustomParameters: []string{"blog"},
	},
	"xing": Provider{
		Name:         "xing",
		RequestURL:   "https://api.xing.com/v1/request_token",
		AuthorizeURL: "https://api.xing.com/v1/authorize",
		AccessURL:    "https://api.xing.com/v1/access_token",
		OAuth:        1,
	},
	"yahoo": Provider{
		Name:         "yahoo",
		RequestURL:   "https://api.login.yahoo.com/oauth/v2/get_request_token",
		AuthorizeURL: "https://api.login.yahoo.com/oauth/v2/request_auth",
		AccessURL:    "https://api.login.yahoo.com/oauth/v2/get_token",
		OAuth:        1,
	},
	"yammer": Provider{
		Name:         "yammer",
		AuthorizeURL: "https://www.yammer.com/dialog/oauth",
		AccessURL:    "https://www.yammer.com/oauth2/access_token.json",
		OAuth:        2,
	},
	"yandex": Provider{
		Name:         "yandex",
		AuthorizeURL: "https://oauth.yandex.ru/authorize",
		AccessURL:    "https://oauth.yandex.ru/token",
		OAuth:        2,
	},
	"zendesk": Provider{
		Name:           "zendesk",
		AuthorizeURL:   "https://[subdomain].zendesk.com/oauth/authorizations/new",
		AccessURL:      "https://[subdomain].zendesk.com/oauth/tokens",
		OAuth:          2,
		ScopeDelimiter: " ",
		Subdomain:      true,
	},
}
